### ISSUE TITLE
功能失效了！

### ISSUE THREAD

**Issue by wpy66666** [EricZhu-42/SteamTradingSiteTracker#1]
老哥挂刀神奇失效啦，抽空维修一下呀，感觉检测时间可以更快为1-0.5个小时这样更方便查询，服务器成本方面可以安排一个打赏功能，我第一次 用这个软件不知道这样行不行，能行我会一份绵薄之力，毕竟要恰饭的嘛

**Comment by EricZhu-42** [comment]
你好，感谢支持！

前几天服务器数据更新延迟的问题现已基本修复。计划内将增加站点状态监控功能，进一步保证数据的时效性。

目前的数据更新速度（重点物品不超过 1.5~2h）的 _收益率_ 基本是最高的 —— 继续提高更新速度需要换用另一个流量更大的请求接口，提高一倍更新频率会导致流量成本增加约 8 倍。考虑到网站目前使用人数较少，短时间内应该会沿用现有的更新速度。

赞助方面，目前服务器成本尚在用爱发电能解决的范围内 😃 。如果喜欢，可以向身边的朋友推荐该网站。后期可能会开放赞助，并为赞助用户提供 _新物品主动推送_ 等更加便捷的功能。
