### ISSUE TITLE
页面打开没数据是我的问题吗？

### ISSUE THREAD

**Issue by Gensokyo1995** [EricZhu-42/SteamTradingSiteTracker#10]
![image](https://user-images.githubusercontent.com/43993884/176574736-7aaaed61-82f7-458b-aebe-aaae65e4b7dc.png)

挂梯子也试过，打开也没数据

**Comment by OreoProMax** [comment]
都一样吧，经典1970年

**Comment by EricZhu-42** [comment]
数据更新策略导致的问题；数据更新异常停止会导致部分物品无法显示。

已修复，这会在统一更新近期没更新的数据，大概 1 小时后所有内容就都恢复正常了。
