### ISSUE TITLE
一个小疑问

### ISSUE THREAD

**Issue by remiliacn** [EricZhu-42/SteamTradingSiteTracker#11]
这边在看您的代码的时候看到这部分，所以想问一个问题

https://github.com/EricZhu-42/SteamTradingSiteTracker/blob/1f3a6b7a5948bcd570006961c08c650a7031ab18/scripts/update_data.py#L212-L214

这部分代码是用来计算用户会收到多少钱的么？

**Comment by remiliacn** [comment]
我这边移植了一下steam市场计算fee的方法，要不要PR一下hhh

**Comment by EricZhu-42** [comment]
可以的，是有更准确的计算方式吗？我没有研究过这边的细节；如果有改进的话欢迎 PR ~

**Comment by remiliacn** [comment]
这个是这样的，在饰品价格较低的情况下可能直接 / 1.15会返回一个实际上更少的输入

一个例子是

| 买家收款 | 卖家支付 | 目前算法收款
------------| --------| --------------
| 1.19 | 1.37 | 1.19
| 1.19 | 1.36 | 1.18
| 1.19 | 1.35 | 1.17
| 1.18 | 1.34 | 1.17
