### ISSUE TITLE
境外IP访问无法访问网站

### ISSUE THREAD

**Issue by Moius** [EricZhu-42/SteamTradingSiteTracker#13]
请问是站长您自行对服务器设置的仅限国内IP访问吗？

**Comment by EricZhu-42** [comment]
你好，

目前没有对访问者的 IP 做特殊限制。

网站服务器位于香港，目前已知境内部分网络环境下可能无法正常访问；境外一般没有问题，但也不排除部分情况下确实无法连接。

如果方便，你可以考虑在更换网络环境后，再次访问网站进行测试。如果依旧无法访问，我打算近期将 DNS 迁移到 cloudflare，可能可以在一定程度上解决问题。

**Comment by ELXIAGHT** [comment]
好的，那我再排查排查，感谢！

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
