### ISSUE TITLE
新的那个悠悠有品存在虚假商品

### ISSUE THREAD

**Issue by Dradows** [EricZhu-42/SteamTradingSiteTracker#14]
AK-47 | 霓虹革命 (久经沙场) 80（其他价格至少90，这个明显特别低）
![QQ截图20221204025349](https://user-images.githubusercontent.com/32986753/205457225-8417b9fb-6d54-4e94-a92e-8eba31a19f5d.png)
![QQ截图20221204025259](https://user-images.githubusercontent.com/32986753/205457226-682934ad-5e65-44d8-863f-64eb6ab8ef49.png)

这把枪如果去平台上购买，会提示向对方发送报价失败，并对对方做出处罚。有没处罚不知道，反正商品并没有下架依然在那摆着。不管这个平台是存在bug还是恶意营销，我觉得都会影响网站数据的可靠性

**Comment by starfish-tech** [comment]
这个问题主要是悠悠有品平台的漏洞，有商家恶意挂低价卡价格然后扰乱市场让别人一键定价就挂出了低价，我感觉很难去排除这种失真数据

**Comment by EricZhu-42** [comment]
你好，

感谢建议！如 @starfish-tech 所说，该问题主要是平台自身的缺陷导致。事实上，之前在其他平台也出现过商品虚假标价的问题。因此：
1. 若问题**不严重** —— 暂不准备对此类商品进行其他处理，留待平台自行解决
2. 若问题**严重** —— 考虑对**长时间未售出的低价饰品**进行过滤

如果虚假标价明显影响了用户的使用体验，我会尝试解决这个问题。

**Comment by Journalist-HK** [comment]
假设A饰品UUYP平台比例比BUFF低，我不勾选UUYP只勾选BUFF的时候，A饰品会用BUFF的价格参加排名还是直接被过滤掉？

**Comment by EricZhu-42** [comment]
> 假设A饰品UUYP平台比例比BUFF低，我不勾选UUYP只勾选BUFF的时候，A饰品会用BUFF的价格参加排名还是直接被过滤掉？

**会用 BUFF 的价格参与排名。**

饰品根据所有已勾选平台的价格中最低的一个参与排名。

**Comment by Tianket** [comment]
如果可以能不能爬前三件或者前五件做平均，毕竟大家也要批量买，排除低定价的影响

**Comment by EricZhu-42** [comment]
> 如果可以能不能爬前三件或者前五件做平均，毕竟大家也要批量买，排除低定价的影响

目前对于*低价饰品*（BUFF 售价低于 8 元的饰品），**平台最低售价**即为第一页前 10 个饰品的平均价格，便于估价批量购入。

对于高价饰品，汇报少数的低定价订单也是有收益的，因此暂时不会使用平均价格。

**Comment by EricZhu-42** [comment]
参考 #22 的意见，考虑在计算*稳定求购比例*时使用价格最低的三个寄售单的平均价格。**此时稳定求购比例受虚假标价的影响相对较小。**

为了保证能够汇报少数的低定价订单，*最优求购比例*将依然使用最低价寄售单的价格。
