### ISSUE TITLE
为什么我访问不了网站了

### ISSUE THREAD

**Issue by doggewzb** [EricZhu-42/SteamTradingSiteTracker#15]
edge提示：
此站点的连接不安全www.iflow.work 使用不受支持的协议。
ERR_SSL_VERSION_OR_CIPHER_MISMATCH
不支持的协议
客户端和服务器不支持常用的 SSL 协议版本或密码套件。

**Comment by EricZhu-42** [comment]
你好，

今天上午九点左右调整了 DNS 设置，目前已经可以正常访问，但可能部分地区因 DNS 更新延时，仍暂时不能访问。

你可以手动刷新 DNS 缓存（如 windows 平台在 cmd 中输入：`ipconfig /flushdns`），或暂时耐心等待；DNS 记录将最晚于 24 小时后自动更新。
