### ISSUE TITLE
我尝试运行代码，遇到了一些问题。

### ISSUE THREAD

**Issue by CVKB** [EricZhu-42/SteamTradingSiteTracker#19]
我好像没有正确配置cookie和数据库。能不能详细介绍一下怎么操作？

**Comment by EricZhu-42** [comment]
目前版本的代码需要配置 Cookie 和 MongoDB，具体的：

Cookie：交易平台获取饰品元数据（ID等）需要带各个平台的登录 Cookie 才能正常访问。
- 可以参考 [update_meta.py](https://github.com/EricZhu-42/SteamTradingSiteTracker/blob/main/scripts/update_meta.py) 第 24-37 行
- 在 BUFF（必选），C5（可选）和UUYP（可选，可能有bug）登陆账号后，在浏览器控制台（F12）打开的情况下浏览平台，一般在 Network 一栏下就能看到带有 Cookie 的请求
- 完整复制 Cookie （应该是文本形式的键值对，以分号分隔）到对应的 `./secrets/[buff|c5|uuyp]_cookie.txt` 文件内即可
- Cookie 设置成功后，[update_meta.py](https://github.com/EricZhu-42/SteamTradingSiteTracker/blob/main/scripts/update_meta.py) 第 24-37 行的三个 assertion 应该可以顺利通过

MongoDB：所有饰品数据均储存在 MongoDB 中
- 本机安装 MongoDB 后，修改 `database.py` 的 `MONGODB_PORT` 为你的 MongoDB 端口即可
- 代码运行起来后，饰品价格数据储存在 `collection="data"`, `database="steam"` 的数据库中；可以使用 `database.py` 中封装的 `get_all_items()` 函数读取数据并使用

后续版本的代码还需要配置 Redis，具体说明将在过几天代码上传后发布。

**Comment by CVKB** [comment]
感谢你的解答，我调试后确实在UUYP出现了BUG。
我先阅读代码吧，研究一下。

期待后续的版本更新。

**Comment by EricZhu-42** [comment]
修正了先前 [Comment ](https://github.com/EricZhu-42/SteamTradingSiteTracker/issues/19#issuecomment-1493195885) 中的描述错误 —— UUYP 应该在物品搜索界面的请求内找到 `authorization` 参数并本地保存。目前版本的代码应当可以正常运行。

似乎 UUYP 的登录态过期较快，BUFF 和 C5 的登录态则能正常使用较长时间？我暂时没有做严格的测试，这只是这几个月维护时的主观印象。

另外，新版本改用异步请求，主要是为了在利用可靠性较低的代理池时，提高并发程度，降低内存消耗。对于一般不使用代理/使用高质量代理隧道，对内存占用不敏感的个人用户来说，可能当前版本更加契合需求？感觉可以考虑将后续版本切换到新的 branch 上另行维护。

**Comment by EricZhu-42** [comment]
基于多进程并行版本的代码已切换至 [sync ](https://github.com/EricZhu-42/SteamTradingSiteTracker/tree/sync) 分支维护。

本地运行遇到的问题可以参考： #19 和 #26
