### ISSUE TITLE
无法跳转到最后一页

### ISSUE THREAD

**Issue by Niubenbenben** [EricZhu-42/SteamTradingSiteTracker#21]
你好非常感谢你做的网站
在使用你们的网站时，我没办法跳转到指定页数，也没办法跳转到最后一页，可以帮忙改进吗？谢谢
![N`0}03ST0W3G%E8Q`I5T7CI](https://user-images.githubusercontent.com/130739267/231971876-e47b6ad3-4db9-416f-a126-97ce58779860.png)

**Comment by EricZhu-42** [comment]
你好，

非常感谢你提出的问题，近期也有其他用户向我们提出类似的需求（见 [APP Issue#2](https://github.com/lazycce/SteamTradingSiteTracker-APP/issues/2)）。其实，在项目初期，我们是打算加入**页数跳转，按比例从高到低排序**等功能，以方便少数反向挂刀的用户的。但经过考虑，我们一直没有添加这些功能。

这主要是因为：我们希望为玩家提供即时、便捷的**挂刀**比例数据信息。我们希望找到市场上**比例最低的饰品**，并将数据提供给用户。因此，在数据获取方面上，我们做了以下两件事：

1. **DOTA2 与 CSGO 的饰品共有约 40000 种，但并不是每一种都适合挂刀**。因此，我们特意设计了一种[筛选算法](https://github.com/EricZhu-42/SteamTradingSiteTracker-Data/blob/main/SteamBuffSnapshot/demo.ipynb)来找出具有挂刀潜力的饰品。目前数据库内约有 15000 种饰品，覆盖了预计 97.5% 以上具有挂刀潜力的饰品。显然大部分比例较高，不适合挂刀的饰品是被排除在外的。这意味着，**站点数据库内比例最高的饰品，很可能并不适合反向挂刀**——站点数据库刻意避开了那些真正的高比例饰品，确保能够快速更新低比例饰品的数据。

2. 玩家挂刀时必然优先选择低比例的饰品。因此，后台会根据饰品当前比例，动态调整其更新频率，确保最先被玩家看到的低比例饰品总是最新的。**这意味着，数据库中高比例的饰品时效性会更差**。

总而言之，如果你希望获取市场上比例最高，最适合反向挂刀的饰品数据，那本项目可能不完全符合你的需求——**数据库内的“高比例“饰品并不是真正意义上的高挂刀比例饰品，其数据时效性也相对较差**。因此，我们一直没有实装按比例由高到低排序等功能。

如果预算充裕，我们会考虑直接追踪所有的 DOTA2 & CSGO 饰品，提供可靠的高比例饰品数据。**但在目前资源受限的情况下，我们的数据更新还是会以低比例饰品为导向。**

如果只是需要快速翻页，可以临时使用以下方法：直接修改网址参数中 `pagenum` 的数值。例如：默认筛选条件下第二页的地址为：

> https://www.iflow.work/steam?platform=buff-igxe-c5-uuyp&game=csgo-dota2&order=buy&pagenum=2&min_price=1.0&max_price=5000.0&min_volume=2

修改其中的 `pagenum=2` 为 `pagenum=X` 即可跳转至第 X 页。请注意：**目前较高页数数据的显示存在 bug**，预计将在新版 UI 上线时修复。
