### ISSUE TITLE
请问可以就是在爬取平台的饰品价格的时候 多爬取下面两个商家的价格吗

### ISSUE THREAD

**Issue by moshangmoyu** [EricZhu-42/SteamTradingSiteTracker#22]
首先感谢大佬的数据库让倒余额变得方便了很多。
请问可以就是在爬取平台的饰品价格的时候 多爬取下面两个卖家的价格吗 饰品十分钟会爬取一次 有些饰品会被扫货机器人一下子扫完，然后再通过数据库去看的时候会出现具体价格和折扣这些对不上的情况，会影响数据的准确性，如果能像steam市场的抓取一样，可以一下爬取前三位的价格然后再进行比例计算，这样数据会准确很多，不然会出现一个饰品的价格对不上然后又十几分钟的时间都是这个饰品的余额比例。

**Comment by EricZhu-42** [comment]
你好，感谢建议！

现在的”稳定求购比例“受到平台价格极值的影响太大，确实不是一个足够”稳定“的指标。

考虑近期调整”稳定求购比例“中平台价格的计算方式：
1. 饰品价格 >= 8 元时：**使用对应平台价格最低的 3 个寄售单的平均价格？或是第三位的价格？**
2. 饰品价格 < 8 元时：仍使用对应平台价格最低的 10 个寄售单的平均价格

后续说明将在调整完成后发布。

**Comment by moshangmoyu** [comment]
好的，感谢您对此项目的热情维护，并积极解决出现的问题，项目组的大佬们都辛苦了。

**Comment by EricZhu-42** [comment]
更新已上线，目前计算 >8 元饰品的**稳定求购比例**时，将使用各平台价格最低的 3 个寄售单的平均价格作为买入价。

更新的具体效果有待观察。预计更新将导致**挂刀指数**出现一定幅度的上涨。

文档&说明的更新将在后续进行。

**Comment by moshangmoyu** [comment]
好的 辛苦了

**Comment by EricZhu-42** [comment]
更新上线后两个多月以来，效果测试良好。

更新后关于三种”挂刀比例”的说明已在[站点主页](https://flowus.cn/share/139253e9-cd71-43c7-9619-b23e6ba14dc1)更新。
