### ISSUE TITLE
你好，页面可以提供一个比例倒序的功能吗？

### ISSUE THREAD

**Issue by yyzim** [EricZhu-42/SteamTradingSiteTracker#23]
大佬们都辛苦了

**Comment by EricZhu-42** [comment]
你好，

详见 Issue #21，**目前数据库更新以低比例饰品为主**，倒序排序后展示的高比例饰品信息准确率较差，预计短时间内不会做这方面的优化。

如果确实需要访问靠后的页面，可以临时参考上述链接中的方法，更改 URL 访问。

请注意：靠后页面的饰品数据与展示可能存在 bug，后续会进行修复。
