### ISSUE TITLE
怎么通过api访问网页数据库？

### ISSUE THREAD

**Issue by kyrosz7u** [EricZhu-42/SteamTradingSiteTracker#24]
RT

**Comment by EricZhu-42** [comment]
你好，

目前服务器运行负载较高，暂时无法提供公开的 API 接口，请见谅。

如果需要访问数据库的历史存档，请参考：[SteamTradingSiteTracker-Data](https://github.com/EricZhu-42/SteamTradingSiteTracker-Data)

如果希望批量获取数据库内的最新数据，请通过[邮箱](mailto:zhuxinhao00@gmail.com)与我联系。需要注意的是，我们无法确保服务 100% 的可用性与准确性，因此不推荐基于我们数据进行商业化项目的开发设计。
