### ISSUE TITLE
环境搭建问题

### ISSUE THREAD

**Issue by Wzj910997331** [EricZhu-42/SteamTradingSiteTracker#25]
1.请问如果是要快速部署，是建议拉去main分支还是sync分支的code?
2.环境搭建需要依赖什么环境？python版本是什么呢？依赖的话只需要MongoDB 和Cookie 就好了吗？

**Comment by Wzj910997331** [comment]
还有请教个问题，请问建议在linux运行还是可以在window也能进行部署

**Comment by EricZhu-42** [comment]
快速部署建议使用 sync 版本的代码。

环境依赖仅需安装 Python + MongoDB 即可。需要配置 cookie 来从交易平台抓取饰品元数据。先运行 `update_meta.py` 抓取饰品元数据（名称，ID 等），再运行 `update_data.py` 抓取实时价格数据。此外，运行过程中需要访问 steamcommunity.com，如果希望大批量抓取的话还需要自行配置代理。

服务器目前是 Ubuntu 18.04 LTS + Python 3.6，但理论上可以在 Windows 或 Python 3.7+ 的环境下正常运行。

**Comment by Wzj910997331** [comment]
ok，非常感谢，我先试一下。。
