### ISSUE TITLE
建议增加三方网站BUFF,C5等求购数据，并且增加steam购买/三方求购的比例

### ISSUE THREAD

**Issue by MercuryN** [EricZhu-42/SteamTradingSiteTracker#27]

**Comment by EricZhu-42** [comment]
钱包余额转卖相关的数据支持暂时不在开发计划之内。

请参考 #21 的回复，本项目为获得更好的挂刀数据进行了大量优化，其代价为：数据库中反向挂刀（余额转卖）的数据可用性较差。如果真的有余额转卖的需求，建议挑 `iflow.work` 没存数据的那些饰品卖（

开发方面，第三方网站的寄售/求购数据 API 基本是独立的，因此加入第三方网站的求购数据需要新发起大量请求，导致数据的更新频率下降约一半。这与网站提供挂刀数据的初衷并不一致，因此暂不考虑进行更新。

**Comment by EricZhu-42** [comment]
关于跨平台交易相关的数据支持已通过[数据 API 服务](https://flowus.cn/share/6fbcab3d-4e7b-42c5-9a8c-918f9ce90b5e)独立提供。

暂不考虑直接在 iflow.work 站点实时提供 **Steam 钱包余额** -> 第三方网站的转卖数据。
