### ISSUE TITLE
建议增加阿根廷区的steam市场价格对比

### ISSUE THREAD

**Issue by Specialweek2023** [EricZhu-42/SteamTradingSiteTracker#29]

**Comment by EricZhu-42** [comment]
我不太了解 Steam Market 交易政策的细节，但饰品在不同地区的价格差异似乎只是由于 Steam 汇率往往延后于现实汇率发生变动。正常情况下，相同饰品在不同地区出售的差价应该不会超过 1%，独立计算各个低价区饰品的价格/比例可能并不会带来明显的收益提升。

如果上述观点存在事实错误，欢迎了解信息的朋友随时指出。

**Comment by luotianyiismywife** [comment]
> 我不太了解 Steam Market 交易政策的细节，但饰品在不同地区的价格差异似乎只是由于 Steam 汇率往往延后于现实汇率发生变动。正常情况下，相同饰品在不同地区出售的差价应该不会超过 1%，独立计算各个低价区饰品的价格/比例可能并不会带来明显的收益提升。
> 
> 如果上述观点存在事实错误，欢迎了解信息的朋友随时指出。

玩家间的市场都是一样的价格，只不过是会按照汇率进行一个换算，所以只要抓一下汇率就行了。
再就是steam的金额最小单位是0.01,不同货币的0.01不一样所以对于一些数字比较大的货币来说竞价会有一定优势。但也聊胜于无。

**Comment by EricZhu-42** [comment]
自 11 月 20 日起，[土区、阿区将使用美元计算游戏价格](https://help.steampowered.com/en/faqs/view/2720-4EC7-B95A-1D2A)。因此，增加阿根廷区的市场价格对比似乎已经不再重要了。

目前站点以国内用户为主。如果后期英语区用户增多，可能考虑在页面上同步显示美元价格。

**Comment by luotianyiismywife** [comment]
我觉得加个港区足矣，反正国人基本都在港区。
抓个汇率的api，前端做一下换算就行了

**Comment by EricZhu-42** [comment]
关于前端货币转换功能的讨论合并至 #52
