### ISSUE TITLE
感谢大佬提供的工具

### ISSUE THREAD

**Issue by Red5Timor** [EricZhu-42/SteamTradingSiteTracker#3]
以及提点建议，是否支持额外的一些筛选（售卖数，价格区间）

**Comment by Red5Timor** [comment]
以及目前只有50个信息，有用信息比例过少

**Comment by EricZhu-42** [comment]
感谢你的建议！

**翻页功能现已支持**，你可以通过点击页面底部的翻页按钮浏览更多的物品信息。

额外的筛选支持（游戏、交易量、价格区间等）将在近期实现。

**Comment by EricZhu-42** [comment]
**游戏 & 价格区间筛选功能现已支持。**

此外，目前优化后的饰品池维护算法不会追踪交易量过低的低价物品，且交易量筛选对用户不是特别友好（主要是阈值很难选），因此暂时不会添加交易量筛选/排序相关的功能。

如果发现确实有必要，会在之后添加相关功能。
