### ISSUE TITLE
价格设置50就这样显示，翻页也这么显示

### ISSUE THREAD

**Issue by zhouchengji** [EricZhu-42/SteamTradingSiteTracker#31]
![image](https://github.com/EricZhu-42/SteamTradingSiteTracker/assets/35595538/3a93b38e-82a9-47e7-b9b1-ed669c34ab35)

**Comment by EricZhu-42** [comment]
你好，

感谢反馈！确实存在这个问题，会尽快处理。

可以先临时使用旧版 UI，测试功能正常。

**Comment by zhouchengji** [comment]
好哦

**Comment by EricZhu-42** [comment]
经确认，是缓存不一致导致的访问错误，线上已修复。

感谢 @lazycce  帮助解决问题~
