### ISSUE TITLE
你好，是否有对“音乐盒”饰品的缺失爬取

### ISSUE THREAD

**Issue by moshangmoyu** [EricZhu-42/SteamTradingSiteTracker#32]
根据我这段时间使用iflow.work的情况来看，似乎没有见到过有buff或者是其他平台的音乐盒相关饰品出现在上面，但根据我长久以来的倒余额经验，音乐盒这个饰品，是浮动不大且比例适中的物品，请问是有什么限制导致的音乐盒无法到网站上吗

**Comment by EricZhu-42** [comment]
Hi,

音乐盒数据是正常爬取的，向后翻几页可能就能看到，例如：

![image](https://github.com/EricZhu-42/SteamTradingSiteTracker/assets/14954473/e75808ea-f7bb-4df0-bc0e-54e803437e82)

FYI，当前时刻数据库中 BUFF 平台最优求购比例最低的 10 种音乐盒物品为：

```
0.7870 音乐盒 | Scarlxrd: 疤王
0.7925 音乐盒 | Juelz - 神枪手
0.7964 引爆器音乐盒集
0.8006 音乐盒（StatTrak™） | Roam - 决心
0.8015 音乐盒（StatTrak™） | Ki:Theory — 莫洛托夫烈火
0.8022 StatTrak™ 决策大师音乐盒集
0.8078 音乐盒 | Noisia - 尖峰时刻
0.8095 音乐盒 | Tim Huling - 新黑色电影
0.8102 音乐盒（StatTrak™） | Daniel Sadowski - 8 位音乐盒
0.8140 音乐盒（StatTrak™） | Meechy Darko - 哥特浮华
```

**Comment by moshangmoyu** [comment]
好的 我明白了 谢谢
