### ISSUE TITLE
可以在页面空白处增加一个换算框吗？

### ISSUE THREAD

**Issue by zhouchengji** [EricZhu-42/SteamTradingSiteTracker#33]
我的构想：在网页的上方空白处设置上下两个框，上面输入现价，下面框自动显示收到的金额（或者左右放置也可以，怎么美观怎么来）。
原因：因为行情站的价格不是实时的，有时候过了一段时间后，价格就变动了，这个变化时常会出现在steam市场价格和行情站价格不同，我知道这里面有个比例，好像是10%，本人数学还一般，算来算去容易出错，故此建议。

**Comment by EricZhu-42** [comment]
Hi, 感谢建议！

关于显示”收到的金额“，目前站点已经支持该功能：在点击饰品后显示的详情窗格中，括号内标注的即为以最低寄售/最高求购价格卖出后到手的金额。例如下图中框出的部分。[新版 UI](https://steam.iflow.work/) 亦提供了该信息。

![image](https://github.com/EricZhu-42/SteamTradingSiteTracker/assets/14954473/5fb7231f-5891-4b21-8a8d-62aa22a93b84)

关于价格变动后的金额显示：确实存在在价格变动后，需要重新计算到手金额及比例的需求。

**考虑后期在页面前端嵌入一个”换算工具“的功能，便于用户使用。**

**Comment by zhouchengji** [comment]
这个寄售价和求购价的换算我看到了，但是因为信息的时效性，当我从旁边steam键点入对应道具的网页时，发现此时市场的求购价和行情站的求购价是不同的，这时我就不知道具体税后价格是什么了

**Comment by EricZhu-42** [comment]
目前挂刀比例计算器的功能已经在 steam.iflow.work 提前上线，感谢 @lazycce 的帮助！

预计七月份我们将进行 UI 重构，完成后 steam.iflow.work 的 UI 将成为默认 UI；可能挂刀比例计算器功能会以 collapse panel 的形式重新布置，便于在浏览数据的同时计算实际比例。

**Comment by EricZhu-42** [comment]
挂刀比例计算器功能已在 [steam.iflow.work](https://steam.iflow.work/) 实装，测试稳定后会合并到默认首页。

使用方法为：点击右上角计算器按钮打开面板，输入购买价格与 Steam Market 出售标价（支持外区货币），显示实际收到的余额及对应的挂刀比例。文档及使用方法待后续更新。

**Comment by EricZhu-42** [comment]
新版 UI 已合并至默认首页，上述功能已实装。
