### ISSUE TITLE
可以添加排序的按钮吗

### ISSUE THREAD

**Issue by C200628** [EricZhu-42/SteamTradingSiteTracker#34]
```
         ▲                ▲                 ▲                 ▲                  ▲ 
日成交量      平台最低售价       最优寄售比例       最优求购比例        稳定求购比例 
         ▼                ▼                 ▼                 ▼                  ▼
```

在每个table后面加上可以排序的按钮
类似于上面这种感觉

**Comment by EricZhu-42** [comment]
感谢建议，后续 UI 更新时考虑支持。应该相较于目前的筛选 - 应用按钮，更加便于使用。

**Comment by EricZhu-42** [comment]
点击表头排序的功能已在 [steam.iflow.work](https://steam.iflow.work/) 实装，测试稳定后将合并到默认首页。

使用方法为：点击四种比例的表头时，会自动切换为使用该比例由低到高排序。文档及使用方法待后续更新。

根据 #23 的讨论，为避免造成误导，表头与设置区仅支持由低到高排序。

**Comment by EricZhu-42** [comment]
新版 UI 已合并至默认首页，上述功能已实装。
