### ISSUE TITLE
鼠标中键点击链接无效

### ISSUE THREAD

**Issue by jascry** [EricZhu-42/SteamTradingSiteTracker#38]
老UI中键点击可以后台打开链接对应平台的标签页，新UI该功能失效。
edge浏览器，版本 117.0.2045.60 (正式版本) (64 位)

**Comment by EricZhu-42** [comment]
“使用鼠标中键在新标签页中打开链接”似乎是部分浏览器的自定义行为。

目前新旧版 UI 所有交易平台（包括旧版 UI 的 Steam Market）的超链接在正常点击后都会在新窗口中打开页面，便于用户同时打开多个页面对比价格。

如果出现了点击链接后，直接在当前页面跳转的情况，欢迎汇报您所使用的浏览器版本。
