### ISSUE TITLE
新版UI排版建议

### ISSUE THREAD

**Issue by yimouleng** [EricZhu-42/SteamTradingSiteTracker#39]
一直不怎么用新版UI，主要是看起来不是很舒服，UE没有旧版的简洁方便。
1. 两边距离太宽了，物品名称会换行，旧版不会自动换行。 换行后看起来就不舒服了，视觉上，可以加宽让新版物品名称保持一行
2. 筛选和排序按钮，还实在下方舒服。 习惯一般是选完鼠标往下移。
3. 模糊搜索+1
4. 排序可以加个更新时间排序配合筛选使用

**Comment by lazycce** [comment]
感谢建议，后续更新时会参考。
针对两边距离太宽了问题，之所以保留这么大的宽度是为了方便在首页添加一些工具（但是现在还未实现）

**Comment by kmck121** [comment]
可以设置一个倒序吗，我是从steam搬到buff，挂刀比例越大利润越高，但是网站好像没有从大到小的功能

**Comment by kmck121** [comment]
我觉得新版ui很好
就是有倒序很好了

**Comment by EricZhu-42** [comment]
上述的部分问题已在新版的 [steam.iflow.work](https://steam.iflow.work/) 界面修复，测试稳定后会合并到默认首页。文档及使用方法待后续更新。

其中：

1. **物品名称过长导致换行的问题已解决。** 对于名称显示不全的情况（一般在宽度 1200~1400px 的设备上出现；不过这部分用户占比非常小），可以点击物品名称来复制完整文本，便于后续搜索。
2. **模糊搜索功能暂不在计划中。**（因为 MongoDB 免费版对中文分词的适配很差；英文会好做很多，但大部分用户不熟悉饰品的英文名）
3. **“更新时间排序”功能通过 #64 近似实现。** 
4. 参考 #23 的讨论，站点显示的饰品大多不适合用来从 Steam 搬到 BUFF。 **为避免造成困惑，倒序排序功能不在计划中。** 如果确实有此类需求，建议参考我们的饰品 API 获得适用于一般交易的完整数据。**不过，目前的 UI 支持页面跳转到最后一页，可以近似实现倒序排序的功能。**

**Comment by EricZhu-42** [comment]
新版 UI 已合并至默认首页，上述问题（除计划外的）已基本解决。
