### ISSUE TITLE
能显示一下steam的求购价吗？

### ISSUE THREAD

**Issue by feeops** [EricZhu-42/SteamTradingSiteTracker#4]
https://www.iflow.work上能显示steam的美元求购价吗？
或者有推算的公式吗？

因为汇率有波动，直接显示美元价应该更好一些

**Comment by feeops** [comment]
悬停没有看到效果啊，我是用的最新版的chrome
或者能依据buff在售价格反推出steam美元价格吗？

**Comment by EricZhu-42** [comment]
稍等，近期还没能抽出时间更新；更新后会发更新公告的。

相关计算公式如下：

最优求购比例 = 平台买入价 / (Steam Market 美元最高求购价 * 美元汇率 / 1.15)。

寄售比例可以同理计算 。

**Comment by feeops** [comment]
美元汇率是写死的还是每天根据央行变化的？

**Comment by feeops** [comment]
对了，挂刀赚余额不累吗？现在steam卡价在4.7元左右，我充了上万元了，还没有红信过

**Comment by feeops** [comment]
buff日交易量是从哪里获取的？我看网页上只有当前在售数量

**Comment by EricZhu-42** [comment]
Steam 会自动对不同区域的货币换算，汇率由 Steam 提供。

...

网站显示的日交易量为 Steam Market 日交易量。

**Comment by EricZhu-42** [comment]
求购价显示功能已于先前更新。

可以通过点击某个饰品来显示其包括求购价在内的详细信息。
