### ISSUE TITLE
网站访问出现问题

### ISSUE THREAD

**Issue by luotianyiismywife** [EricZhu-42/SteamTradingSiteTracker#42]
![图片](https://github.com/EricZhu-42/SteamTradingSiteTracker/assets/81459639/82055f59-aeb0-4bd2-b01e-518b1dcf1e49)
是因为cloudfare炸了么

**Comment by EricZhu-42** [comment]
11月5日上午8时，服务器数据更新正常，但不排除因其他问题导致服务器短时间无法访问。

如果出现短期的服务器无法访问情况，可以稍等一会后再次尝试访问；若服务器长期无法访问，可以通过 Github Issue，邮件等方式向我反馈。我会尽量确保网站 7*24 小时可用。
