### ISSUE TITLE
考虑过加一个邮件订阅服务嘛，达到三十天最优惠的时候发个邮件提醒一下

### ISSUE THREAD

**Issue by gp3174787533** [EricZhu-42/SteamTradingSiteTracker#45]

**Comment by EricZhu-42** [comment]
感谢建议，可以考虑的，技术实现难度很低，但不确定是否有足够多的用户有此类需求，以及希望在何种条件下收到通知？

此 Issue 将保持开放，欢迎有类似需求的朋友加入讨论！

**Comment by gp3174787533** [comment]
比如优于本月 90% 的时间发送邮件提醒，或者自己设置筛选条件过后定时发送邮件返回数据

**Comment by shaw465** [comment]
感觉有必要，可以邮件或者RSS的形式，否则只能写个爬虫什么的了

**Comment by yzhEric** [comment]
支持

**Comment by Alexis-Li** [comment]
这个完全可以作为你们项目组的一份额外收入，用于服务高强度挂刀用户，大部分普通用户直接去网站看就好了。订阅会员让用户选择一个他关注的价格区间，或者合适的挂刀比例，然后发送邮件

**Comment by EricZhu-42** [comment]
邮件订阅的主要复杂度在于：

  1. 需要创建一个页面，允许用户设置希望的筛选方式、触发条件和通知方式
  2. 每日轮询所有用户设置的触发条件，并检查是否需要发送邮件，是否近期已发送邮件（避免发送过于频繁）
  3. 主动发送订阅邮件需要引入额外的邮件服务提供商

邮件订阅系统基本没有技术难点，但需要做一套新的页面、API 及定时任务，需要一定的开发量，近期我们可能没有足够的空闲时间来完成。

如果有朋友希望实现一个类似的功能，可以联系我，我很乐意提供所需的 API。邮件订阅功能将保持在更新计划中，但暂时无法预估具体的完成时间。

最后，我们没有对个人用户提供付费服务的计划，包括此处的邮件订阅功能。

**Comment by gp3174787533** [comment]
> 邮件订阅的主要复杂度在于：
> 
> 1. 需要创建一个页面，允许用户设置希望的筛选方式、触发条件和通知方式
> 2. 每日轮询所有用户设置的触发条件，并检查是否需要发送邮件，是否近期已发送邮件（避免发送过于频繁）
> 3. 主动发送订阅邮件需要引入额外的邮件服务提供商
> 
> 邮件订阅系统基本没有技术难点，但需要做一套新的页面、API 及定时任务，需要一定的开发量，近期我们可能没有足够的空闲时间来完成。
> 
> 如果有朋友希望实现一个类似的功能，可以联系我，我很乐意提供所需的 API。 邮件订阅功能将保持在更新计划中，但暂时无法预估具体的完成时间。
> 
> 最后，我们没有对个人用户提供付费服务的计划，包括此处的邮件订阅功能。

可以提供数据查询的接口吗？

**Comment by EricZhu-42** [comment]
关于挂刀指数查询接口，如果有需求，我们可以公开提供。

此外，我们已经以 [DataDump](https://github.com/EricZhu-42/SteamTradingSiteTracker-Data?tab=readme-ov-file) 的形式公开提供了延时 0~12 小时的完整数据。考虑到市场整体行情一般不会在一天内发生大幅变化，该数据应该足够实现所需的行情监测及提醒功能。

**Comment by gp3174787533** [comment]
如下图数据可以开发接口供轮询吗？
![image](https://github.com/user-attachments/assets/cf8ba668-e505-42c1-83d8-25ebe17526df)

**Comment by EricZhu-42** [comment]
我们公开提供如下两个接口：

  1. https://api.iflow.work/steam/analysisData 用于查询自 2022/04/19 以来的详细挂刀指数历史
      - 该数据与 “行情分析” 界面图表的数据一致
  3. https://api.iflow.work/steam/analysisTakeaway 用于查询当天的 10% 挂刀指数及其在历史数据（本月、本季度、本年）中的排位
      - 该数据与首页 “行情摘要” 显示的数据一致
      - 由于部分用户将 “行情摘要” 显示的挂刀比例理解为挂刀的实际折扣，我们可能会在之后将其修改为 5% 或 2% 挂刀指数，使之与用户理解更加一致。该接口返回的历史数据排位信息应该可作为相对稳定的，能够反映当前挂刀合适程度的指标。

**Comment by Aristokun** [comment]
我可以帮忙编写服务 邮件服务商问题不大 我另一服务一直使用个人邮箱 发送内容累计数万 目前没有问题 
但目前网站没有用户账户管理，邮箱如果随意添加订阅，有被拿去恶意利用的风险，对服务压力大，对用户可能是垃圾邮件。
这方面如何避免

**Comment by Octopus058** [comment]
写成RSS怎么样？可以在网站上方提示RSS和使用手册（#76）

**Comment by gp3174787533** [comment]
> 我可以帮忙编写服务 邮件服务商问题不大 我另一服务一直使用个人邮箱 发送内容累计数万 目前没有问题 但目前网站没有用户账户管理，邮箱如果随意添加订阅，有被拿去恶意利用的风险，对服务压力大，对用户可能是垃圾邮件。 这方面如何避免

限制每日通知数量，支持邮件退订，添加订阅的时候发送邮箱验证码验证是否是别人操作，可以避免大部分吧

**Comment by Aristokun** [comment]
> > 我可以帮忙编写服务 邮件服务商问题不大 我另一服务一直使用个人邮箱 发送内容累计数万 目前没有问题 但目前网站没有用户账户管理，邮箱如果随意添加订阅，有被拿去恶意利用的风险，对服务压力大，对用户可能是垃圾邮件。 这方面如何避免
> 
> 限制每日通知数量，支持邮件退订，添加订阅的时候发送邮箱验证码验证是否是别人操作，可以避免大部分吧

是 验证码就可以解决了 我可以编写后台服务 比如api形式提供  但前台页面我做的不行 得寻求合作

**Comment by zjzjg1280** [comment]
和邮件订阅并行的没有可以和类似 telegramm软件 做阈值订阅消息的

**Comment by gp3174787533** [comment]
有道理，可以整个QQ群或者微信群，整个机器人，每天播报一下行情，大家还能一起交流交流，看倒什么东西



---原始邮件---
发件人: "Jinguang ***@***.***&gt;
发送时间: 2024年10月1日(周二) 晚上10:08
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;"State ***@***.***&gt;;
主题: Re: [EricZhu-42/SteamTradingSiteTracker] 考虑过加一个邮件订阅服务嘛，达到三十天最优惠的时候发个邮件提醒一下 (Issue #45)




 
和邮件订阅并行的没有可以和类似 telegramm软件 做阈值订阅消息的

**Comment by Octopus058** [comment]
现在加了7天冷却，已经失去倒的欲望了:(
