### ISSUE TITLE
同名饰品匹配错误

### ISSUE THREAD

**Issue by 1027603857** [EricZhu-42/SteamTradingSiteTracker#46]
今天"印花 | 炸弹小队（闪亮）"饰品匹配错误，首页的0.1的求购比，实际上是不同的饰品被匹配到一起了

https://steamcommunity.com/market/listings/730/Sticker%20%7C%20Bomb%20Squad%20(Foil)
https://steamcommunity.com/market/listings/730/Sticker%20%7C%20Bombsquad%20(Foil)

**Comment by EricZhu-42** [comment]
感谢提醒，由于 [Sticker | Bomb Squad (Foil)](https://steamcommunity.com/market/listings/730/Sticker%20%7C%20Bomb%20Squad%20(Foil)) 和 [Sticker | Bombsquad (Foil)](https://steamcommunity.com/market/listings/730/Sticker%20%7C%20Bombsquad%20(Foil)) 的中文名均为 印花 | 炸弹小队（闪亮），导致匹配出现错误。

该问题已在 [Commit ](https://github.com/EricZhu-42/SteamTradingSite-ID-Mapper/commit/25186fc5b33c44f5b34bd35cb73437fc5c9a0448)中修正。
