### ISSUE TITLE
可以咨询一下开发者们用的是什么代理池吗？

### ISSUE THREAD

**Issue by 1027603857** [EricZhu-42/SteamTradingSiteTracker#47]
非常感谢大家的工作，我想在本地运行爬虫，但是一直找不到好用的代理

**Comment by 1027603857** [comment]
> Hi，目前我们主要用的是 [BrightData](https://brightdata.com/) - 他们的 0.6$/GB 的 Datacenter Proxy 非常符合我们的需求。
> 
> * 我很希望在这放一个 aff 推广链接，但似乎他们只对企业用户做推广 :(
> 
> 此外，我们亦通过自建的代理池（代理源主要来自于一些 GitHub 仓库）代理了部分流量。然而，付费代理成本仍然是我们的最主要支出项。

感谢回答，我也一直在用BrightData，但是没有注意到这个套餐。
另外你们的服务器是境外的吗？我找了很多免费代理池，但是代理steam市场都不通

**Comment by EricZhu-42** [comment]
我们用于数据更新的服务器位于香港。

境内的服务器有时无法顺利连接到境外的代理池，无论是免费还是付费代理。如果希望获取 Steam 市场的数据，建议使用境外的服务器部署服务。
