### ISSUE TITLE
能加入成交量筛选选项吗

### ISSUE THREAD

**Issue by Vennye** [EricZhu-42/SteamTradingSiteTracker#5]
大多数时候都想尽快卖出去，很多饰品比例好但是可能挂很久都卖不出去的。我自己挂刀的时候一般都选日成交量几百以上的饰品

**Comment by EricZhu-42** [comment]
感谢反馈！

可以的，大概 1~2 周内会完成，近期略有些忙。

增加筛选项的工作量很小，不过需要调整 UI 的位置，会稍麻烦些。

**Comment by EricZhu-42** [comment]
功能已实现，可以通过界面右侧 “交易筛选” 的控件，设置与日成交量相关的筛选参数。

另：晚些会重新设计筛选功能的 UI。
