### ISSUE TITLE
大佬我写了一个工具想集成你的这个网站

### ISSUE THREAD

**Issue by ohuo133233** [EricZhu-42/SteamTradingSiteTracker#51]
如题，可以提供API或者什么建议吗？
还有集成你这个会影响你的版权吗？
可以联系我吗？QQ：144128924

**Comment by EricZhu-42** [comment]
Hi,

- 如果是网页外链形式的引用，随时欢迎，无需告知我们；
- 如果是使用 Priority 数据库的公开 Datadump（即 [SteamTradingSiteTracker-Data](https://github.com/EricZhu-42/SteamTradingSiteTracker-Data) 项目数据，每 12 小时上传一次），可以随意使用，注明数据来源即可；
- 其他情况，请联系 [zhuxinhao00@gmail.com](mailto:zhuxinhao00@gmail.com)，并请告知您的需求及大致方案。
