### ISSUE TITLE
建议添加货币转换功能

### ISSUE THREAD

**Issue by chuciy** [EricZhu-42/SteamTradingSiteTracker#52]
具体价格栏可以支持不同汇率，比如美金，方便外区账号使用，不然在确认求购价是否仍一致的时候比较麻烦

**Comment by ParanoiaIsGreat** [comment]
+1，方便外区小号

**Comment by EricZhu-42** [comment]
Hi，感谢建议！抱歉近期比较忙，一直没能抽出时间做这个功能。

目前**货币汇率转换**及**比例计算器工具**（#33 ）是我们优先级最高的新功能（详见：[开发计划](https://www.yuque.com/null_42/steam/nzv1y85u3babgzfp)），预计最晚七月份可以上线。

**Comment by EricZhu-42** [comment]
目前临时的货币汇率转换功能已在 steam.iflow.work 上线，感谢 @lazycce 的帮助！

预计七月份我们将进行 UI 重构，完成后 steam.iflow.work 的 UI 将成为默认 UI。届时货币汇率将从服务器端获取，无需手动填写。此外，我们会调整外币价格的展示方式，以获得更好的展示效果。

**Comment by EricZhu-42** [comment]
货币转换功能已在 [steam.iflow.work](https://steam.iflow.work/) 实装，测试稳定后将合并到默认首页。

使用方法为：在右上角的汇率切换按钮中选择货币。该设置会影响展开物品展开列表显示的售出价格，及比例计算器面板中的售出价格。文档及使用方法待后续更新。

**Comment by EricZhu-42** [comment]
新版 UI 已合并至默认首页，上述功能已实装。
