### ISSUE TITLE
新UI应用筛选换行了

### ISSUE THREAD

**Issue by dropDBToRun** [EricZhu-42/SteamTradingSiteTracker#56]
1080p 屏幕缩放100% chrome缩放100%
![image](https://github.com/EricZhu-42/SteamTradingSiteTracker/assets/77114795/9c447026-c470-4230-b8a9-44e111dc7a7d)

**Comment by EricZhu-42** [comment]
Hi，

感谢反馈！目前我们正在对原有的 UI 做一些调整，通过 Chrome devtool 的测试，主流分辨率下的显示效果应该是正常的，但也可能存在一些适配不完全的情况，请见谅。

五一假期结束后，我会优先处理 UI 分辨率这边的问题。

**Comment by EricZhu-42** [comment]
更新后的 UI 已合并至默认首页，目前针对主流设备（移动端，或宽度 1600px 以上的桌面端）应当均有正常的显示效果。

如更新后 UI 仍存在相应问题，请在下方回复，我们会重新打开该 issue
