### ISSUE TITLE
建议添加曼恩钥匙比例作为挂刀指数的另一个参考指标

### ISSUE THREAD

**Issue by TonySue2000** [EricZhu-42/SteamTradingSiteTracker#58]
曼恩钥匙作为steam市场上流动性最好的商品，其之于倒余额市场，相当于美国十年期国债之于金融市场，乃市场的锚
可将曼恩钥匙的比例显示于网页抬头，作为一个直观的提醒，其意为，若比例高于此，就不要白忙活倒其他的东西了

**Comment by EricZhu-42** [comment]
Hi，感谢建议！抱歉我不是 CSGO 玩家，不太熟悉 CSGO 道具的具体情况。选择部分交易量较大的物品（可能一般是钥匙或胶囊？）比例作为参考比例的方案显然是合理的 —— 可以考虑基于历史数据，筛选一些交易量大，短期价格波动相对较小的饰品作为参考。

不过，每个人会有不同的交易策略。我们设计挂刀指数的目的是便于用户在交易时做出决策。例如，目前的 N%-挂刀指数提供的是关于“何时应该开始下场屯余额，何时又应该停手”的信息。

如果新增一个以参考物品比例为基准的指标，可能实际上不会改变大部分用户的交易行为 —— 大部分人都是筛选交易量较大的饰品，然后根据求购或寄售比例，由低到高挑选饰品。因此，若其他物品的比例高于参考物品，则用户一般会自然地选择参考物品进行交易；提供一个常驻的参考物品比例似乎不太能起到额外的帮助。

如果其他朋友有相关的需求或想法，欢迎留言评论，我们可以看看是否有后期实现的必要性。

**Comment by lb-fes** [comment]
> Hi，感谢建议！抱歉我不是 CSGO 玩家，不太熟悉 CSGO 道具的具体情况。

他说的应该是[TF2钥匙](https://steamcommunity.com/market/listings/440/Mann%20Co.%20Supply%20Crate%20Key?l=schinese)，不是CSGO的道具，基本上都在8折以上。

**Comment by TonySue2000** [comment]
是我毒奶的原因吗？buff把整个军团要塞2都下架了，大悲
