### ISSUE TITLE
目前行情站无法获取C5GAME饰品价格

### ISSUE THREAD

**Issue by nanfengzhiyi** [EricZhu-42/SteamTradingSiteTracker#60]

**Comment by EricZhu-42** [comment]
感谢提醒，因 C5 接口调整，目前 C5 购买/求购价格获取功能暂时失效，我们会在近期恢复更新。其他平台的数据更新不受影响，

**Comment by EricZhu-42** [comment]
C5 数据更新已恢复，iflow.work 的 C5 数据已经基本更新到最新，可以正常使用；API 的全量数据预计一天内更新完成。

**Comment by kumitom** [comment]
请问现在c5是又停了吗？

**Comment by EricZhu-42** [comment]
> 请问现在c5是又停了吗？

Hi，从5月26日起（大致时间），C5对价格获取接口部署了反爬虫措施。尽管我们于5月27日测试过能够绕开反爬，但这会显著增加我们及平台方的资源消耗；我们也无意违抗平台方的反爬意图。因此，我们暂时停止了 C5 相关的数据更新，该消息已经在 iflow.work 主页公布。

**Comment by kumitom** [comment]
> > 请问现在c5是又停了吗？
> 
> Hi，从5月26日起（大致时间），C5对价格获取接口部署了反爬虫措施。尽管我们于5月27日测试过能够绕开反爬，但这会显著增加我们及平台方的资源消耗；我们也无意违抗平台方的反爬意图。因此，我们暂时停止了 C5 相关的数据更新，该消息已经在 iflow.work 主页公布。

原来如此，感谢解答~
