### ISSUE TITLE
各平台的售卖比例以及排行

### ISSUE THREAD

**Issue by awdsz12580** [EricZhu-42/SteamTradingSiteTracker#61]
可以加一个各平台的同一件商品的售卖价格对比的比例百分比。
比如：
uuyp√    steam√    buff    c5
售卖比例排行（不算手续费）√（算手续费steam手续费）
1.印花集         uuyp： steam—— 1   ：1.4——0.71
2.格洛克         buff ： steam—— 1.1 ：1.4——0.78
3.黑色魅影     igex ： steam—— 1.2 ：1.4——0.85

**Comment by awdsz12580** [comment]
也可以是各平台的求购对比售卖排行

**Comment by EricZhu-42** [comment]
Hi，抱歉回复较晚；目前网站点击某个饰品后展开的细节菜单应当已能显示多个平台的价格，但显示“多个平台的比例”可能会有些信息冗余 —— 目前四个平台四种比例，展开后如果显示 4*4=16 个数字可能对用户有些不太友好。

![image](https://github.com/EricZhu-42/SteamTradingSiteTracker/assets/14954473/80ad6abb-9caa-42ea-80fb-d0dce5f1d8db)

**Comment by EricZhu-42** [comment]
更新后的 UI 已合并至默认首页，其中 “饰品比例计算器” 功能可以计算任意价格对应的挂刀比例。如更新后 UI 仍存在相应问题，请在下方回复，我们会重新打开该 issue
