### ISSUE TITLE
有的饰品有时候会显示有时候不显示

### ISSUE THREAD

**Issue by ehehela** [EricZhu-42/SteamTradingSiteTracker#62]
以”Copenhagen 2024 Challengers Sticker Capsule“为例，有时候会显示，有时候（过几个小时去看）不显示，筛选条件没变

**Comment by EricZhu-42** [comment]
Hi，饰品列表是根据其挂刀比例动态维护的，因此有两种可能：

1. **此时**该物品挂刀比例**较高**，因此排序较为靠后，多翻几页可以看到
2. **近期**该物品挂刀比例**持续较高**，因此已经从 Priority 数据库中剔除（每天自 03:12 起，我们每四个小时进行一次数据库调整）。此时饰品不在高频更新列表中，其数据不在网站显示，但我们依然在后台定期更新其价格（至多 24 小时一次；当其挂刀比例降低时会重新回到  Priority 数据库中，保持高频更新）

**Comment by ehehela** [comment]
你好，挂刀比例是指什么，这个饰品是成交量特别大的，第一页就能看到（如果它显示的话），如果它不显示，我往后翻了好几页也没找到。此外，我还把筛选成交量调成5000+，依然没有找到它（如果它不显示的话）

**Comment by EricZhu-42** [comment]
目前我们采用 **$0.7 \times $最优求购比例 $+ 0.3 \times $最优寄售比例** 作为对饰品挂刀效果的综合评估指标，取所有 CSGO & Dota2 饰品中**该指标最低的 4000 种饰品**维护于 Priority 数据库中（即网站上可以查询到的饰品集合）。

因此，如果在网站上没有查到，一般是因为当前该饰品比例较高，不契合大部分用户的挂刀需求，因此我们没有在 Priority 数据库中更新并保存其价格信息。如果目前希望获取所有在售饰品的价格（24小时更新一次），可以参考我们的[数据 API](https://www.yuque.com/null_42/steam/glmytl66g4l4sufg)。

在服务器有负载余量的情况下，后期我们也可能会提供一些 Base 数据库上的搜索功能，便于有其他需求的用户使用。
