### ISSUE TITLE
建议界面添加根据更新时间进行筛选的功能

### ISSUE THREAD

**Issue by Tang-Shieheng** [EricZhu-42/SteamTradingSiteTracker#64]
已知受限于服务器成本和单位时间请求量限制，更新频率暂时无法做到更高。但‘过时’数据确实参考意义不大，是否考虑在web界面增加一个“更新时间”的筛选条件。能够根据个人需要剔除掉‘过时’数据

**Comment by EricZhu-42** [comment]
筛选更新时间的功能已在 [steam.iflow.work](https://steam.iflow.work/) 实装，测试稳定后会合并到默认首页。

使用方法为：在 "筛选与排序设置" -> "高级设置" 中设置时效范围，设为 0 则表示不启用。文档及使用方法待后续更新。

**Comment by Tang-Shieheng** [comment]
已经在使用了，个人感觉效果很好，大佬辛苦了
