### ISSUE TITLE
点击平台价格不会再显示比价详情了？

### ISSUE THREAD

**Issue by Remonli** [EricZhu-42/SteamTradingSiteTracker#66]
之前点击一次buff，会新标签打开平台页面，同时打开比价详情，可以看到各个平台价格和steam价格，然后点击steam，会弹出新steam页面，同时关闭比价详情。

现在点击buff图标，只会打开buff页面，不会打开比价详情了。

这样的问题是还要回头单独点击行来看详情。

能不能改回之前的逻辑啊？比较方便。

**Comment by EricZhu-42** [comment]
Hi，请问是指 https://steam.iflow.work/ 的新 UI，还是 https://www.iflow.work/ 的旧版 UI 呢？

近几天旧版 UI 应该会下线，统一使用新 UI

**Comment by Remonli** [comment]
是旧的https://www.iflow.work/cn?platform=buff&game=csgo-dota2&order=buy&pagenum=1&min_price=1&max_price=5000&min_volume=2，

新的https://steam.iflow.work/正常，这么说我之前一直访问的是新的？ 那没问题了，谢谢！
