### ISSUE TITLE
新UI鼠标中键点击交易平台或者steam无法在后台打开新标签了

### ISSUE THREAD

**Issue by roseway** [EricZhu-42/SteamTradingSiteTracker#67]
不确定是不是我浏览器的问题，现在只能左键单击在前台打开新页面，不利于一次性多开几个看现在的比例。但是旧的ui是可以的。

**Comment by EricZhu-42** [comment]
Hi，感谢提醒；该问题已在线上版本修复，现在所有平台链接均默认在新标签页打开，可以使用鼠标中键在后台打开。
