### ISSUE TITLE
新版界面移动端饰品价格详情错误

### ISSUE THREAD

**Issue by TedXiongfeng** [EricZhu-42/SteamTradingSiteTracker#68]
![image.png](https://github.com/user-attachments/assets/b529324a-7583-48eb-a626-86f4395a7564)

最低寄售价和最高求购价反了。寄售价比求购价还低

**Comment by EricZhu-42** [comment]
感谢反馈！线上版本已修正该问题，文档图例预计近期修正。

**Comment by EricZhu-42** [comment]
文档图例已修正
