### ISSUE TITLE
太猛啦

### ISSUE THREAD

**Issue by lllliang** [EricZhu-42/SteamTradingSiteTracker#7]
网页端可以爬取嘛QAQ
爬取有什么限制嘛

**Comment by lllliang** [comment]
大佬 ，你爬取buff的时候直接get，不需要模拟登录操作嘛

**Comment by EricZhu-42** [comment]
具体细节可以参考 scripts 目录内的代码。

其中，元数据 (meta) 部分需要模拟登录；数据 (data) 部分无需登录。

**Comment by lllliang** [comment]
噢噢好哒，谢谢。
