### ISSUE TITLE
前端参数中的 min_volume=1000 生效了，但是展示不对

### ISSUE THREAD

**Issue by Chen-23333** [EricZhu-42/SteamTradingSiteTracker#70]
如图所示
![image](https://github.com/user-attachments/assets/34dd8bb8-f88d-48ec-8d0c-29773c053c48)

**Comment by EricZhu-42** [comment]
感谢反馈！该 BUG 是实现 #34 功能时，初始化顺序设置错误导致的。

目前线上版本已经修正该问题。
