### ISSUE TITLE
希望筛选能够使用售出价作为条件

### ISSUE THREAD

**Issue by ReallyChooseC** [EricZhu-42/SteamTradingSiteTracker#71]
现在只能大概估计一下价格然后一个个打开去看
能否支持筛选售出价（扣steam税后）？

**Comment by EricZhu-42** [comment]
Hi，近期会考虑支持该功能。

因为基本设置区空间不够了，初步想法是在“高级设置”中加一个切换“购买价”和“售出价”的选项，后期会再做 UI 布局的优化。

**Comment by EricZhu-42** [comment]
“按售出价筛选”的功能已实装，其中筛选使用的价格为“排序依据”所对应的 Steam 市场售出到手余额。

如存在使用问题，欢迎反馈。
