### ISSUE TITLE
我记得以前是有C5的数据的，突然发现没了

### ISSUE THREAD

**Issue by Alexis-Li** [EricZhu-42/SteamTradingSiteTracker#72]
我感觉C5，BUFF，UU，这三个网站国内用的多，反倒是ECO没多少人用，有没有考虑恢复C5平台的数据呢？

**Comment by EricZhu-42** [comment]
Hi，请参考 #60, #63 讨论。我们已与 C5 有过初步接触，但暂未获得对方关于数据合作的进一步反馈。

我们会持续关注该问题。

**Comment by EricZhu-42** [comment]
C5 数据已于 2024/09/04 恢复接入，目前运行状态基本正常。感谢 C5 官方的支持！
