### ISSUE TITLE
EDGE 筛选与排序设置

### ISSUE THREAD

**Issue by weixianjun** [EricZhu-42/SteamTradingSiteTracker#73]
用EDGE浏览器打开网页 筛选与排序设置旁边没有 基本设置 和 应用规则 这两个选项 是怎么回事

**Comment by weixianjun** [comment]
![Uploading QQ20240826-193244.png…]()

**Comment by weixianjun** [comment]
后续重置了所有设置 可以了 不清楚edge有什么设置会导致这个问题

**Comment by EricZhu-42** [comment]
好的，不排除是不是缓存问题。理论上站点前端在大部分浏览器（Chrome, Edge, Firefox, Safari 等）上的显示效果基本一致，如果出现问题，可以考虑清除缓存（或开无痕模式）试试。
