### ISSUE TITLE
ECO平台的价格延迟较大

### ISSUE THREAD

**Issue by lanvent** [EricZhu-42/SteamTradingSiteTracker#74]
按照最优寄售排序，点进ECO里的价格稳定比网站里的价格高很多。下图里的这把枪ECO很久没有库存了，但它的价格一直没有变成“无”。

![image](https://github.com/user-attachments/assets/a19e1ffc-ede0-4a3e-85eb-318cf7aaffa7)

**Comment by EricZhu-42** [comment]
感谢反馈！因 API 问题，目前 ECO 平台数据更新暂时停止，预期短期内会恢复。

**Comment by EricZhu-42** [comment]
更新已恢复，目前主页显示的物品数据均正常。再次感谢提醒！
