### ISSUE TITLE
部分饰品的 ECO 实时价格存在延时

### ISSUE THREAD

**Issue by lolodaf** [EricZhu-42/SteamTradingSiteTracker#78]

**Comment by EricZhu-42** [comment]
Hi，感谢反馈！我们检查了 ECO 价格的显示情况，确实存在类似的问题。

例如，对于如下物品：

![image](https://github.com/user-attachments/assets/9132069d-6f5c-410f-88f4-deff4da542b2)

此时显示的最低售价为 10.32￥；打开 ECO 的物品详情界面，信息如下：

![image](https://github.com/user-attachments/assets/9c01d607-23d9-4e6e-861e-c4680de89f8b)

可以看到此时 ECO 返回的 ”起售价格” 确实为 10.32￥，但实际订单中的最低价为 13.94￥

由于我们直接从 ECO 官方接口获取数据，可能受到平台缓存等机制影响，导致价格更新存在延迟，请见谅。后面我们会与平台方联系，看能否解决这个问题。

**Comment by lolodaf** [comment]
麻烦了，如修复完成请告知一下

**Comment by EricZhu-42** [comment]
ECO 官方已于 2024/11/08 修复该问题。经过一周多的观察，线上没有再出现明显的价格延时问题。

感谢 @lolodaf 的提醒与 ECO 官方的协助！
