### ISSUE TITLE
 请问关于刷新时间

### ISSUE THREAD

**Issue by trojantrog** [EricZhu-42/SteamTradingSiteTracker#8]
可以主动刷新吗

**Comment by EricZhu-42** [comment]
你好！受服务器成本限制，目前数据刷新统一由服务器后台控制，暂不支持用户主动刷新。

具体的数据更新策略可参考 [update_data.py](https://github.com/EricZhu-42/SteamTradingSiteTracker/blob/main/scripts/update_data.py)，目前大致是每 **40 min** 批量更新一次队列前端的物品；前几页物品的最长更新间隔一般不会超过 2 小时。

**Comment by 1024191579** [comment]
建议放个爱发电，zf截图啥的

**Comment by 1024191579** [comment]
> 你好！ 受服务器成本限制，目前数据刷新统一由服务器后台控制，暂不支持用户主动刷新。
> 
> 具体的数据更新策略可参考 [update_data.py](https://github.com/EricZhu-42/SteamTradingSiteTracker/blob/main/scripts/update_data.py)，目前大致是每 **40 min** 批量更新一次队列前端的物品； 前几页物品的最长更新间隔一般不会超过 2 小时。

建议放个爱发电，zf截图啥的

**Comment by 1024191579** [comment]
已经4个小时没有更新了 呜呜呜

**Comment by EricZhu-42** [comment]
网站主页的 "Support the site" 界面可以看到捐助的收款码。

数据更新的部分掉线了，现在已经修复。
