### ISSUE TITLE
cdn.jsdelivr.net抽风问题

### ISSUE THREAD

**Issue by gouduyao** [EricZhu-42/SteamTradingSiteTracker#9]
cdn.jsdelivr.net日常抽风，要不考虑换个？

**Comment by EricZhu-42** [comment]
感谢，好像确实存在这个问题。我这两天看看有没有其他更好的解决方案。

**Comment by EricZhu-42** [comment]
已经转移到了 cdnjs，国内应该可以正常使用了。

不过由于 web 服务器放在香港，暂时无法备案，无法对大陆地区的访问做 CDN 加速，因此访问不稳定的问题还是很难彻底解决。

**Comment by gouduyao** [comment]
套个cf？

**Comment by gouduyao** [comment]
我看你是直接解析到腾讯ip的，不行就套个cf

**Comment by EricZhu-42** [comment]
cf 只对企业用户提供国内的 CDN 节点；如果用国外的节点不确定有没有优化效果。

另外，目前网站静态资源很少，传输的主要内容是动态获取的饰品价格数据，也比较难做缓存。

晚些我可能会把前端重做一下，到时候测试一下 cf 的效果怎么样吧。

**Comment by gouduyao** [comment]
抱歉时隔一年又来回复提问题了，期间也不时使用大佬的网站来挂刀，因为我自己本身的网络环境你懂的，没太关注过网站卡不卡的问题，然后最近看已经上到cf解析了，关于国内加载慢的问题，之前有看到过三网分别解析不同的CFIP，然后三网最优CFIP有程序可以跑的，再接着就是用程序自动更新解析了，具体文章找不到了，大佬如果有空的话可以看看

**Comment by EricZhu-42** [comment]
感谢建议！自 2024/02 起，我们部署了 Cloudflare 三网优选 IP 的脚本。根据近两个月的观察，网站目前在全国 95% 地区不同网络环境下均可以正常访问，先前因网络原因无法打开网站的情况已经极大缓解。
